"""empty message

Revision ID: 3a8565d1b06a
Revises: 85f6b94daea7
Create Date: 2024-12-11 14:29:22.223292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a8565d1b06a'
down_revision = '85f6b94daea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
